# Generated by Django 4.1.7 on 2023-03-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_amenity_property_num_of_guests_property_province_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyAvailability',
        ),
    ]
