# Generated by Django 4.1.7 on 2023-03-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_thisuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='thisuser',
            name='username',
            field=models.CharField(default='user_a', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
