# Generated by Django 4.1.7 on 2023-03-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_thisuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thisuser',
            name='username',
        ),
    ]
