# Generated by Django 4.1.7 on 2023-03-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_thisuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='thisuser',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
    ]
