# Generated by Django 4.1.7 on 2023-03-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_thisuser_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='thisuser',
            name='password2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
