# Generated by Django 4.1.7 on 2023-03-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_thisuser_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisuser',
            name='password1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thisuser',
            name='password2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
