# Generated by Django 4.1.7 on 2023-03-14 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyavailability_remove_property_amenities_and_more'),
        ('accounts', '0011_alter_thisuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='request_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
